v = input('Digite um valor ')
print('O tipo primitivo desse valor é {} '.format(type(v)))
print('Só tem espaço? {} '.format(v.isspace()))
print('É um numero? {} '.format(v.isnumeric()))
print("É Alfanumerico? {} ".format(v.isalnum()))
print('É Alfabético? {} '.format(v.isalpha()))
print('Está em maiúscula? {} '.format(v.isupper()))
print('Esta em minúscula? {} '.format(v.islower()))
print('Esta capitalizada? {} '.format(v.istitle()))
